### ISSUE TITLE
Transparency in PNG not supported

### ISSUE THREAD

**Issue by alter3go** [acmanderson/content-aware#2]
If CAS is fed a PNG with transparency, it converts the transparency to black at some point in the process.

Input:

![Pizza](http://www.cicis.com/media/1138/pizza_trad_pepperoni.png)

Result:

![CASsed Pizza](http://i.imgur.com/fGvpbSR.png)

**Comment by alter3go** [comment]
The same may be true of GIFs; I haven't confirmed this though.

**Comment by acmanderson** [comment]
I think this was fixed when I implemented the Wand library instead of using Popen in [https://github.com/acmanderson/content-aware-santa/commit/202d1175f5ce66dfa3cd9626e1f21b87d9367b45](this commit). Testing locally images retain their transparency. The version we were using needs to be updated.
![new_687474703a2f2f7777772e63696369732e636f6d2f6d656469612f313133382f70697a7a615f747261645f7065707065726f6e692e706e67](https://cloud.githubusercontent.com/assets/4852024/22910985/24675e2c-f223-11e6-801a-a3e9f9d5232a.png)
